# DictConfig tips
# Use the value ??? to indicate parameters that need to be set prior to access
# null should be the equivalent of "None"

defaults:
  - general: train
  - dataset: classification_binary
  - embedder: esm2_t6_8M
  - dimred: noreduction
  - predictor: logisticregression_fast
  - persistence: local
  - mlflow: local
  - plots: plot
